### ISSUE TITLE
Refactor Build Phases Roadmap

### ISSUE THREAD

**Issue by jcampbell05** [jcampbell05/xcake#40]
This issue is to keep track of the improvements or features we need with Build Phases in Xcake.

- [x] Add support for inferring build phases from target i.e Adding embed build phases for a watch app.
- [x] Add support for custom build phases by the `Cakefile` author. i.e Custom build scripts.
- [x] Continue support for inferring build phases based on files included i.e add copy files build phase for resource files.

#37 introduces some of the capabilities listed above but we need to consider a long term architecture for pulling these off. I spiked some ideas and here are some of the steps I feel need to be taken:

- [x] Add support for target dependancies which will make it easier to detect which target is implementing an apple watch or unit test in the generation phase (Rather than the hack based on the Target name we have right now). This will be needed for Target inferred build phases. (Implemented in #41)
- [x] Introduce some sort of context which allows generators to or a way to map targets to native targets. Thats way we can run a second pass for generators that require the native project objects to be created. Such as target dependency generators, scheme generators and build phase generators.
- [x] Abstract build phase generator system so that File inferred build phases, target inferred build phases and custom build phases are generated using as many shared classes as possible (I want to avoid having 3 different systems for generating these build phases).
- [x] Abstract file installer system, related to the above.

These will be updated as we implement or discover more steps.

**Comment by jcampbell05** [comment]
Will aim to achieve some sort of abstract build phase system by v0.6.5 - v0.7.0
